/-
Copyright (c) 2026. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
-/
import DolevYao.Derivable

/-!
# Protocol Secrecy — A Minimal Authentication Fragment

We instantiate the Dolev-Yao model with a two-message protocol between
Alice and Bob sharing a symmetric key `kAB`:

    Message 1: Alice → Bob:   enc ⟨nA, Alice⟩ kAB
    Message 2: Bob → Alice:   enc nA kAB

Alice generates a fresh nonce `nA`, pairs it with her name, encrypts with
the shared key, and sends. Bob decrypts, extracts the nonce, and echoes it
back encrypted — a minimal challenge-response.

We prove that a Dolev-Yao attacker who observes both messages but does not
know `kAB` cannot derive the nonce `nA`.

## Main results

* `DolevYao.nonce_secret` — the attacker cannot derive `nA`

## Proof strategy

Both protocol messages are encrypted under `kAB`, so they satisfy
`guarded nA kAB`. The key `kAB` is not guarded (it would need to differ
from itself). By `guarded_of_derivable`, everything the attacker can derive
is guarded. But `nA` is not guarded (it would need to differ from itself).
Contradiction.
-/

namespace DolevYao

open Term

/-! ### Protocol constants -/

/-- The nonce generated by Alice. -/
abbrev nA : Term := .atom "nA"

/-- The shared symmetric key between Alice and Bob. -/
abbrev kAB : Term := .atom "kAB"

/-- Alice's identity. -/
abbrev alice : Term := .atom "Alice"

/-- Message 1: Alice → Bob: `enc ⟨nA, Alice⟩ kAB` -/
abbrev msg1 : Term := .enc (.pair nA alice) kAB

/-- Message 2: Bob → Alice: `enc nA kAB` -/
abbrev msg2 : Term := .enc nA kAB

/-! ### Secrecy theorem -/

/-- **Nonce secrecy.** The attacker cannot derive `nA` from the protocol
messages alone.

The proof has three steps:
1. The key `kAB` is not guarded (`kAB ≠ kAB` fails).
2. Both messages are guarded (each is encrypted under `kAB`).
3. By invariant preservation, everything derivable is guarded — but `nA`
   is not guarded (`nA ≠ nA` fails). Contradiction. -/
theorem nonce_secret : ¬ Derivable {msg1, msg2} nA := by
  intro hd
  -- Step 1: the key is not guarded (it cannot differ from itself)
  have hkey : ¬ guarded nA kAB kAB := fun h => h.2 rfl
  -- Step 2: both protocol messages are guarded (encrypted under kAB)
  have hs : ∀ s ∈ ({msg1, msg2} : Finset Term), guarded nA kAB s := by
    intro s hs
    simp only [Finset.mem_insert, Finset.mem_singleton] at hs
    rcases hs with rfl | rfl <;> exact Or.inl rfl
  -- Step 3: nA would have to be guarded, but it isn't
  exact (guarded_of_derivable hkey hd hs).1 rfl

/-- The parameterized form from the problem statement. -/
theorem nonce_secret' (initial : Finset Term)
    (h_init : initial = {enc (pair nA (atom "Alice")) kAB, enc nA kAB}) :
    ¬ Derivable initial nA := by
  subst h_init
  exact nonce_secret

end DolevYao
